// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopsRUsAPi.Data;

namespace ShopsRUsAPi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210228120524_CreateInvoice2")]
    partial class CreateInvoice2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ShopsRUsAPi.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datecreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNum")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAffiliate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isEmployee")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ShopsRUsAPi.Models.Discount", b =>
                {
                    b.Property<long>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("ShopsRUsAPi.Models.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("billDiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<long>("customerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("discountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("totalDiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("totalproductAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("customerId");

                    b.HasIndex("discountId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ShopsRUsAPi.Models.Items", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("invoicesId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isGrocery")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("itemAmount")
                        .HasColumnType("TEXT");

                    b.Property<long>("productId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("invoicesId");

                    b.HasIndex("productId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ShopsRUsAPi.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGroccery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopsRUsAPi.Models.Invoice", b =>
                {
                    b.HasOne("ShopsRUsAPi.Models.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopsRUsAPi.Models.Discount", "discount")
                        .WithMany()
                        .HasForeignKey("discountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("discount");
                });

            modelBuilder.Entity("ShopsRUsAPi.Models.Items", b =>
                {
                    b.HasOne("ShopsRUsAPi.Models.Invoice", "invoices")
                        .WithMany("Items")
                        .HasForeignKey("invoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopsRUsAPi.Models.Product", "products")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("invoices");

                    b.Navigation("products");
                });

            modelBuilder.Entity("ShopsRUsAPi.Models.Invoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
